### ISSUE TITLE
8gpu CUDA out of memory

### ISSUE THREAD

**Issue by tuntun990606** [SungFeng-Huang/Meta-TTS#5]
I used 8 GPUs for training, and set shots and queries to 3, meta batchsizes is set to 8. And set batchsize in config/train/base.yaml is set to 48, grad_ acc_ Step is set to 8. But when the code runs, it still reports CUDA out of memory. What else do I need to change?

**Comment by SungFeng-Huang** [comment]
What kind of GPUs do you use? In my experiments, I use V100, which has 32 GB memory per GPU. If you're using GPUs with less memory, then it might report CUDA OOM.

Besides, grad_acc_step does not need to set to 8 if you already have 8 GPUs. Each meta-update is calculated from (grad_acc_step * meta_batchsize) meta-tasks, so setting both to 8 means each meta-update uses 8*8=64 meta-tasks.
Also, the batchsize in config/train/base.yaml only affect baseline training, which does nothing to meta training.

If it is still hard to get rid of CUDA OOM problem, you could try to use a smaller model (setup in config/model/base.yaml) or fewer inner-steps (e.g. change [this line](https://github.com/SungFeng-Huang/Meta-TTS/blob/85c228c0a277e066e525fab959088aad5c59d293/config/algorithm/meta_emb_vad.train_all.1-shot.yaml#L29))

**Comment by tuntun990606** [comment]
My gpu has 11g. I choose the meta_table_emd_va model for training. When I set meta_batchsize=1 query=shot=3, I can set a piece of gpu, such as gpu=0 for training. But once I set mechabatchsize=8, gpu：-1 will show  problems with cuda.

**Comment by tuntun990606** [comment]
> Thank u!I change the step! The problem is solved now！
